In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

In [3]:
import pandas as pd

In [4]:
data=pd.DataFrame(boston.data, columns=boston.feature_names)

In [5]:
data['MEDV']=pd.DataFrame(boston.target)

In [6]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [7]:
pd.DataFrame(data.corr().round(2))

CRIM    ZN  INDUS  CHAS   NOX    RM   AGE   DIS   RAD   TAX  PTRATIO  \
CRIM     1.00 -0.20   0.41 -0.06  0.42 -0.22  0.35 -0.38  0.63  0.58     0.29   
ZN      -0.20  1.00  -0.53 -0.04 -0.52  0.31 -0.57  0.66 -0.31 -0.31    -0.39   
INDUS    0.41 -0.53   1.00  0.06  0.76 -0.39  0.64 -0.71  0.60  0.72     0.38   
CHAS    -0.06 -0.04   0.06  1.00  0.09  0.09  0.09 -0.10 -0.01 -0.04    -0.12   
NOX      0.42 -0.52   0.76  0.09  1.00 -0.30  0.73 -0.77  0.61  0.67     0.19   
RM      -0.22  0.31  -0.39  0.09 -0.30  1.00 -0.24  0.21 -0.21 -0.29    -0.36   
AGE      0.35 -0.57   0.64  0.09  0.73 -0.24  1.00 -0.75  0.46  0.51     0.26   
DIS     -0.38  0.66  -0.71 -0.10 -0.77  0.21 -0.75  1.00 -0.49 -0.53    -0.23   
RAD      0.63 -0.31   0.60 -0.01  0.61 -0.21  0.46 -0.49  1.00  0.91     0.46   
TAX      0.58 -0.31   0.72 -0.04  0.67 -0.29  0.51 -0.53  0.91  1.00     0.46   
PTRATIO  0.29 -0.39   0.38 -0.12  0.19 -0.36  0.26 -0.23  0.46  0.46     1.00   
B       -0.39  0.18  -0.36  0.05 -0.38  0.13 -0.27  0.29 -0.44 -0.44    -0.18   
LSTAT    0.46 -0.41   0.60 -0.05  0.59 -0.61  0.60 -0.50  0.49  0.54     0.37   
MEDV    -0.39  0.36  -0.48  0.18 -0.43  0.70 -0.38  0.25 -0.38 -0.47    -0.51   

            B  LSTAT  MEDV  
CRIM    -0.39   0.46 -0.39  
ZN       0.18  -0.41  0.36  
INDUS   -0.36   0.60 -0.48  
CHAS     0.05  -0.05  0.18  
NOX     -0.38   0.59 -0.43  
RM       0.13  -0.61  0.70  
AGE     -0.27   0.60 -0.38  
DIS      0.29  -0.50  0.25  
RAD     -0.44   0.49 -0.38  
TAX     -0.44   0.54 -0.47  
PTRATIO -0.18   0.37 -0.51  
B        1.00  -0.37  0.33  
LSTAT   -0.37   1.00 -0.74  
MEDV     0.33  -0.74  1.00

In [8]:
x=data[['RM','ZN']]

In [9]:
x

RM    ZN
0    6.575  18.0
1    6.421   0.0
2    7.185   0.0
3    6.998   0.0
4    7.147   0.0
..     ...   ...
501  6.593   0.0
502  6.120   0.0
503  6.976   0.0
504  6.794   0.0
505  6.030   0.0

[506 rows x 2 columns]

In [10]:
y=data['MEDV']

In [11]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x=pd.DataFrame(x)
y=pd.DataFrame(y)

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [15]:
y_train

MEDV
342  16.5
154  17.0
146  15.6
48   14.4
70   24.2
..    ...
184  26.4
430  14.5
115  18.3
289  24.8
158  24.3

[404 rows x 1 columns]

In [16]:
from sklearn.tree import DecisionTreeRegressor

In [17]:
dt1=DecisionTreeRegressor(max_depth=20)

In [18]:
dt1.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=20)

In [22]:
y_pred1=dt1.predict(x_test)

In [23]:
import numpy as np

In [24]:
from sklearn.metrics import mean_squared_error

In [25]:
np.sqrt(mean_squared_error(y_test, y_pred1))

7.712861679954959

In [26]:
from sklearn.ensemble import RandomForestRegressor

In [27]:
rf1=RandomForestRegressor()

In [28]:
rf1.fit(x_train, y_train)

<ipython-input-28-f548204f8abb>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf1.fit(x_train, y_train)


RandomForestRegressor()

In [29]:
rf1.score(x_test,y_test)

0.4532865107029036

In [30]:
y_pred2=rf1.predict(x_test)

In [31]:
np.sqrt(mean_squared_error(y_test, y_pred2))

6.915906784778213

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
from sklearn.datasets import load_digits

In [34]:
digits = load_digits()

In [35]:
x_train, x_test, y_train, y_test=train_test_split(
digits.data,digits.target,test_size=0.25)

In [36]:
dt2=DecisionTreeClassifier(criterion="entropy")

In [37]:
dt2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [38]:
dt2.score(x_test,y_test)

0.8577777777777778

In [31]:
dt3=DecisionTreeClassifier(max_depth=30)

In [32]:
dt3.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=30)

In [33]:
dt3.score(x_test,y_test)

0.9298245614035088

Q. Using iterations, and the classification/regression models,
try to identify the optimum max_depth value
at which the following 3 models give the maximum R2 score.
1. Decision Tree Regressor
2. Random Forest Regressor
3. Decision Tree Classifier

### Decision Tree Classifier

In [44]:
from sklearn.tree import DecisionTreeClassifier

In [45]:
from sklearn.datasets import load_breast_cancer

In [46]:
cancer_dataset = load_breast_cancer()

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_test,y_train,y_test = train_test_split(cancer_dataset.data,cancer_dataset.target,test_size=0.2)

In [49]:
dt=DecisionTreeClassifier(max_depth=30)

In [54]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=30)

In [55]:
y_pred=dt.predict(x_test)

In [56]:
from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(y_test,y_pred)
print(cf_matrix)

[[46  7]
 [ 3 58]]


In [57]:
import numpy as np
cf_matrix=np.transpose(np.transpose(cf_matrix)/cf_matrix.astype(float).sum(axis=1))
cf_matrix

array([[0.86792453, 0.13207547],
       [0.04918033, 0.95081967]])

### Logistic Regression

In [3]:
from sklearn.datasets import load_breast_cancer

In [4]:
cancer_dataset = load_breast_cancer()

In [5]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(cancer_dataset.data,cancer_dataset.target,test_size=0.2)

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
logReg1 = LogisticRegression(max_iter=10000)

In [8]:
logReg1.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [9]:
y_pred=logReg1.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(y_test,y_pred)
print(cf_matrix)

[[39  1]
 [ 5 69]]


In [11]:
import numpy as np
cf_matrix=np.transpose(np.transpose(cf_matrix)/cf_matrix.astype(float).sum(axis=1))

In [12]:
cf_matrix

array([[0.975     , 0.025     ],
       [0.06756757, 0.93243243]])